### ISSUE TITLE
URLs with no protocol

### ISSUE THREAD

**Issue by asieira** [afilipovich/gglsbl#18]
When I submit URLs with no protocol I'm getting an exception on `lookup_url`:
```
>>> sbl.lookup_url('www.google.com:443/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/gglsbl/client.py", line 112, in lookup_url
    list_names = self._lookup_hashes(url_hashes)
  File "/usr/local/lib/python2.7/site-packages/gglsbl/client.py", line 122, in _lookup_hashes
    full_hashes = list(full_hashes)
  File "/usr/local/lib/python2.7/site-packages/gglsbl/protocol.py", line 163, in hashes
    for url_variant in self.url_permutations(self.canonical):
  File "/usr/local/lib/python2.7/site-packages/gglsbl/protocol.py", line 188, in canonical
    host = full_unescape(url_parts.hostname)
  File "/usr/local/lib/python2.7/site-packages/gglsbl/protocol.py", line 171, in full_unescape
    uu = urllib.unquote(u)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib.py", line 1234, in unquote
    bits = s.split('%')
AttributeError: 'NoneType' object has no attribute 'split
```

Is it required to have a full and well-formed URL to perform the query? If so, maybe it would be better to check for that explicitly and raising a ValueError instead.

**Comment by afilipovich** [comment]
According to Google spec URLs without scheme should be prefixed with "http://", so I've made a fix for this particular case.
