### ISSUE TITLE
KeyError: 'matches'

### ISSUE THREAD

**Issue by secureli** [afilipovich/gglsbl#20]
File "build/bdist.linux-x86_64/egg/gglsbl/client.py", line 92, in _sync_full_hashes
KeyError: 'matches'

My python code for looking up multiple urls is as follows:

input_file = open('alexa.csv', 'r') # this is from alexa.com's top 1mm domain list, sanitized so its one domain per line

for line in input_file:
  sbl.lookup_url(str.rstrip(line))

**Comment by afilipovich** [comment]
@secureli, knowing what input triggers the error would be helpful.
Can you please run this code with extra debugging? Something like
```input_file = open('alexa.csv', 'r') 
for line in input_file:
    print(line)
    sbl.lookup_url(str.rstrip(line))
```

**Comment by secureli** [comment]
That fixed it - the issue was newlines at the end of the file. Thank you!

**Comment by afilipovich** [comment]
Ok, thanks, I've added input validation with more meaningful error.

**Comment by Stack-Attack** [comment]
Hello,

I'm having a similar issue on a small fraction of URL's, and I'm looking for clarification on whether this is a limitation or a bug. Here's an example trace:
`gglsbl_client.py --check-url https://twitter.com/XEO092/status
2018-04-04 11:30:58,203 INFO Opening SQLite DB safe_browse
2018-04-04 11:30:58,382 INFO Rolling back DB transaction.
Traceback (most recent call last):
  File "\gglsbl-master\bin\gglsbl_client.py", line 86, in <module>
    main()
  File "\gglsbl-master\bin\gglsbl_client.py", line 71, in main
    bl = sbl.lookup_url(args.check_url)
  File "\gglsbl\client.py", line 120, in lookup_url
    list_names = self._lookup_hashes(url_hashes)
  File "\gglsbl\client.py", line 166, in _lookup_hashes
    self._sync_full_hashes(matching_prefixes.keys())
  File "\gglsbl\client.py", line 97, in _sync_full_hashes
    for m in fh_response['matches']:
KeyError: 'matches'`

The URL's are pulled from tweets automatically, but also fail on a manual submission. Example URL's:

https://twitter.com/XEO092/status
http://ebay.eu/
http://www.inspirepattaya.com/lifestyle/whats-missing-table/

**Comment by afilipovich** [comment]
Hi @Stack-Attack, I cannot replicate this error, could you please try to update `gglsbl` to the latest version v1.4.10, sync local cache and repeat the query?

**Comment by Stack-Attack** [comment]
Thanks @afilipovich, after updating and re-syncing local cache the error has been resolved. My apologies for not verifying the version myself beforehand. Keep up the awesome work!
