### ISSUE TITLE
403 Error on Sync

### ISSUE THREAD

**Issue by Stefan-Code** [afilipovich/gglsbl#3]
When I try to sync the database with this snippet:
```python
from gglsbl import SafeBrowsingList
sbl = SafeBrowsingList("secret")
sbl.update_hash_prefix_cache()
```
I get an exception: ```urllib2.HTTPError: HTTP Error 403: Forbidden```
I added a bit of logging, so the ouput is:
```
init
Next query will be delayed 158 seconds

Opening SQLite DB ./gsb_v3.db
Retrieving prefixes
Sleeping for 158 seconds

performing api call to https://safebrowsing.google.com/safebrowsing/downloads?appver=0.1&pver=3.0&key=...&client=api with payload: goog-malware-shavar;
googpub-phish-shavar;

Traceback (most recent call last):
  File "sync.py", line 3, in <module>
    sbl.update_hash_prefix_cache()
  File "C:\Users\SK\Programming\gglsbl\gglsbl\client.py", line 28, in update_hash_prefix_cache
    response = self.prefixListProtocolClient.retrieveMissingChunks(existing_chunks=existing_chunks)
  File "C:\Users\SK\Programming\gglsbl\gglsbl\protocol.py", line 222, in retrieveMissingChunks
    raw_data = self._fetchData(existing_chunks)
  File "C:\Users\SK\Programming\gglsbl\gglsbl\protocol.py", line 205, in _fetchData
    response = self.apiCall(url, payload)
  File "C:\Users\SK\Programming\gglsbl\gglsbl\protocol.py", line 62, in apiCall
    response = urllib2.urlopen(request)
  File "C:\Python27\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 410, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 448, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 531, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```
Any idea what's going on?
EDIT: I'm sure the API Key is correct, btw. The Google Implementation works.

**Comment by Stefan-Code** [comment]
Didn't realize there are different API Keys for v2.2 and v3.0 needed. Sorry :)

**Comment by afilipovich** [comment]
Thanks for pointing that out. I've added a note to README.
