### ISSUE TITLE
HTTP Error 413: Request Entity Too Large

### ISSUE THREAD

**Issue by sb542** [afilipovich/gglsbl#35]
I'm able to run update_hash_prefix_cache() a number of times to update the local database. But on about the 8th update Google's servers return an HTTP 413 error. Looks like the payload may be too large?

**Comment by afilipovich** [comment]
Hi, can you please provide stack trace? Sync process involves several calls to Google API, it would he helpful to know which one triggers the error.

**Comment by sb542** [comment]
This error occurs after deleting the SQLite db file in /tmp

Traceback (most recent call last):
  File "update_gsb.py", line 39, in <module>
    sbl.update_hash_prefix_cache()
  File "build/bdist.linux-x86_64/egg/gglsbl4/client.py", line 28, in update_hash_prefix_cache
    response = self.prefixListProtocolClient.retrieveMissingChunks(existing_chunks=existing_chunks)
  File "build/bdist.linux-x86_64/egg/gglsbl4/protocol.py", line 228, in retrieveMissingChunks
    raw_data = self._fetchData(existing_chunks)
  File "build/bdist.linux-x86_64/egg/gglsbl4/protocol.py", line 211, in _fetchData
    response = self.apiCall(url, payload)
  File "build/bdist.linux-x86_64/egg/gglsbl4/protocol.py", line 64, in apiCall
    response = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 413: Request Entity Too Large

**Comment by afilipovich** [comment]
Trace looks like from rather old `gglsbl` version which uses legacy GSB v2 protocol no longer supported by Google. Updating to the latest `gglsbl` should fix this (it is also faster and more reliable).
