### ISSUE TITLE
Quota exceeded  when using gglsbl-rest

### ISSUE THREAD

**Issue by pczzy** [afilipovich/gglsbl#45]
Traceback (most recent call last):
  File "/data1/antiphish/antiphish/gglrsbl/gglsbl-rest/app.py", line 29, in _lookup
    return sbl.lookup_url(url)
  File "/data1/antiphish/anaconda2/lib/python2.7/site-packages/gglsbl/client.py", line 131, in lookup_url
    list_names = self._lookup_hashes(url_hashes)
  File "/data1/antiphish/anaconda2/lib/python2.7/site-packages/gglsbl/client.py", line 180, in _lookup_hashes
    self._sync_full_hashes(matching_prefixes.keys())
  File "/data1/antiphish/anaconda2/lib/python2.7/site-packages/gglsbl/client.py", line 103, in _sync_full_hashes
    fh_response = self.api_client.get_full_hashes(hash_prefixes, client_state)
  File "/data1/antiphish/anaconda2/lib/python2.7/site-packages/gglsbl/protocol.py", line 43, in wrapper
    r = func(*args, **kwargs)
  File "/data1/antiphish/anaconda2/lib/python2.7/site-packages/gglsbl/protocol.py", line 150, in get_full_hashes
    response = self.service.fullHashes().find(body=request_body).execute()
  File "/data1/antiphish/anaconda2/lib/python2.7/site-packages/googleapiclient/_helpers.py", line 130, in positional_wrapper
    return wrapped(*args, **kwargs)
  File "/data1/antiphish/anaconda2/lib/python2.7/site-packages/googleapiclient/http.py", line 842, in execute
    raise HttpError(resp, content, uri=self.uri)
HttpError: <HttpError 429 when requesting https://safebrowsing.googleapis.com/v4/fullHashes:find?alt=json&key=xxx0mXbAXx5AXUTc5frwo5NOwsHZdSgwrvg returned "Quota exceeded for quota group 'UpdateAPIGroup' and limit 'CLIENT_PROJECT-1d' of service 'safebrowsing.googleapis.com' for consumer 'project_number:612173722054'.">

**Comment by afilipovich** [comment]
Looks like you are sending more requests than 1-day quota imposed by Google. You can find more info and usage stats in your Google Developer Dashboard.
