### ISSUE TITLE
When I try to sync the database, I have got the error as follows:

### ISSUE THREAD

**Issue by tuxxon** [afilipovich/gglsbl#5]
>>> from gglsbl import SafeBrowsingList
>>> sbl = SafeBrowsingList("secret key for 3.0")
>>> sbl.update_hash_prefix_cache()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/gglsbl-0.4-py2.7.egg/gglsbl/client.py", line 26, in update_hash_prefix_cache
    response = self.prefixListProtocolClient.retrieveMissingChunks(existing_chunks=existing_chunks)
  File "/usr/local/lib/python2.7/dist-packages/gglsbl-0.4-py2.7.egg/gglsbl/protocol.py", line 220, in retrieveMissingChunks
    raw_data = self._fetchData(existing_chunks)
  File "/usr/local/lib/python2.7/dist-packages/gglsbl-0.4-py2.7.egg/gglsbl/protocol.py", line 203, in _fetchData
    response = self.apiCall(url, payload)
  File "/usr/local/lib/python2.7/dist-packages/gglsbl-0.4-py2.7.egg/gglsbl/protocol.py", line 60, in apiCall
    response = urllib2.urlopen(request)
  File "/usr/lib/python2.7/urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden

My key is for protocol 3.0. 
Any help?

**Comment by tuxxon** [comment]
sorry. The key is not for 3.0.  It was for 2.2.
